[project]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "3D-private"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "jupyter lab"

[dependencies]
python = ">=3.12.5,<4"
pip = ">=24.2,<25"
meshio = ">=5.3.5,<6"
autograd = ">=1.7.0,<2"
numpy = ">=2.1.0,<3"
matplotlib = ">=3.9.2,<4"
jupyterlab = ">=4.1.8,<5"
jupyterlab-myst = ">=2.4.2,<3"

[pypi-dependencies]
mpl3d = { git = "https://github.com/rougier/matplotlib-3d.git" }
sdf = { git = "https://github.com/fogleman/sdf.git" }
